#!/usr/bin/env node
'use strict';
/*
 * Generates PocketKit's rolling schedule of trial coupons (same scheme as the Piano Atlas app).
 *
 * A coupon's expiry is baked into the app, so issuing a new one would otherwise mean a new build and a Play
 * review. Pre-baking two years of fortnightly codes means you just hand out whichever code covers today.
 * Only the HASHES go in the app (www/js/coupons.js), so the codes cannot be read out of the APK.
 *
 *   node tools/generate-coupons.js                      # 52 fortnightly codes starting yesterday (UTC)
 *   node tools/generate-coupons.js 2026-10-04 52 14     # start date, count, days per window
 *
 * Writes:  www/js/coupons.js        (hashes; shipped)
 *          coupon-codes.txt         (PLAINTEXT codes; project root, NOT shipped -- keep it private, never commit it)
 */
const crypto = require('crypto'), fs = require('fs'), path = require('path');
const ROOT = path.join(__dirname, '..');
const SALT = 'PocketKit/coupon/v1';                  // must match COUPON_SALT in www/js/pro.js
const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no I, O, 0, 1: easy to read aloud and type

// Windows open at 00:00Z, so default to YESTERDAY (UTC): a schedule starting "today" is not live yet east of UTC.
const FORCE = process.argv.includes('--force');
process.argv = process.argv.filter(a => a !== '--force');
if (fs.existsSync(path.join(ROOT, 'coupon-codes.txt')) && !FORCE) {
  console.error('coupon-codes.txt already exists. Generating again makes every code you already handed out stop working.');
  console.error('Run with --force to replace it (the old file is kept as coupon-codes.<timestamp>.txt).');
  process.exit(1);
}
const startArg = process.argv[2] || new Date(Date.now() - 86400000).toISOString().slice(0, 10);
const COUNT = Number(process.argv[3] || 52), DAYS = Number(process.argv[4] || 14);
const start = Date.parse(startArg + 'T00:00:00Z');
if (!Number.isInteger(COUNT) || COUNT < 1 || !Number.isInteger(DAYS) || DAYS < 1) { console.error('count and days must be positive whole numbers'); process.exit(1); }
if (FORCE && fs.existsSync(path.join(ROOT, 'coupon-codes.txt'))) fs.renameSync(path.join(ROOT, 'coupon-codes.txt'), path.join(ROOT, 'coupon-codes.' + Date.now() + '.txt'));
if (!Number.isFinite(start)) { console.error('bad start date:', startArg); process.exit(1); }

const group = n => Array.from({ length: n }, () => ALPHABET[crypto.randomInt(ALPHABET.length)]).join('');
const newCode = () => ['PKT', group(4), group(4), group(4), group(4)].join('-'); // 16 random chars ≈ 1.2e24 combinations
const sha256 = s => crypto.createHash('sha256').update(SALT + s).digest('hex');
const day = 86400000, fmt = ms => new Date(ms).toISOString().slice(0, 10);

const rows = [], seen = new Set();
for (let i = 0; i < COUNT; i++) {
  let code; do { code = newCode(); } while (seen.has(code)); seen.add(code);
  rows.push({ n: i + 1, code, hash: sha256(code), opensAt: fmt(start + i * DAYS * day),
    expiresAt: new Date(start + (i + 1) * DAYS * day - 1000).toISOString().replace('.000Z', 'Z') }); // windows tile with no gap
}
const devCode = ['PKT', 'DEV', group(4), group(4), group(4)].join('-'); // 10 minutes from redemption; debug builds only

const js = `/* GENERATED by tools/generate-coupons.js -- hashes only, the codes themselves are not in the app.
   expiresAt is absolute (never "N days after redemption"), so reinstalling cannot renew a trial. */
const COUPONS = [
${rows.map(r => `  { hash: '${r.hash}', opensAt: '${r.opensAt}T00:00:00Z', expiresAt: '${r.expiresAt}', label: 'Fortnight ${String(r.n).padStart(2, '0')}' },`).join('\n')}
  { hash: '${sha256(devCode)}', devMinutes: 10, label: 'Dev short trial' }
];
`;
fs.writeFileSync(path.join(ROOT, 'www', 'js', 'coupons.js'), js, 'utf8');
const txt = ['PocketKit trial coupons -- KEEP PRIVATE (do not commit, do not ship).', '',
  '#   code                    hand out from   stops working',
  ...rows.map(r => `${String(r.n).padStart(2, '0')}  ${r.code}   ${r.opensAt}      ${r.expiresAt.slice(0, 10)}`), '',
  `dev ${devCode}   (10 minutes from redemption, debug builds only)`, '',
  `${rows.length} codes, ${DAYS}-day windows, ${rows[0].opensAt} to ${rows[rows.length - 1].expiresAt.slice(0, 10)}.`,
  'Expiry is absolute: a code redeemed late in its window only grants the remainder of that window.'].join('\r\n');
fs.writeFileSync(path.join(ROOT, 'coupon-codes.txt'), txt, 'utf8');
console.log(`wrote www/js/coupons.js (${rows.length + 1} entries) and coupon-codes.txt`);
